# Токен бота
token: "sosi"

settings:
  # Айди роли которой доступна команда
  roleID: 1235
  # Минимальное время таймаута (в часах, только цельное число)
  minTime: 1
  # Максимальное время таймаута (в часах, только цельное число)
  maxTime: 6

messages:
  # Сообщение самой рулетки
  roulette:
    embed:
      # Заголовок эмбеда
      title: "Поздравляю!"
      # Описание эмбеда
      description: "%target% стал счастливым победителем в русскую рулетку! 🐒"
      # Первое поле (немного говняно сделано, но ладно)
      field1:
        # Заголовок поля
        title: "Ведущий:"
        # Описание поля
        description: "%executor%"
      # Второе поле (немного говняно сделано, но ладно)
      field2:
        # Заголовок поля
        title: "Срок:"
        # Описание поля
        description: "%time% ч."
      # Вложение эмбеда
      image: "https://media.discordapp.net/attachments/397055707486355466/1138514461808935013/result.gif?ex=65f9c238&is=65e74d38&hm=e6d0f024f804247cd36bb7b738d5b03b1208c255ae02973ee639136441339d61"
      # Цвет эмбеда
      color: 764ADD